### ISSUE TITLE
combine `fd` and `eva_id` arguments into one admin type

### ISSUE THREAD

**Issue by max-ruttenberg** [bespoke-silicon-group/bsg_f1#103]
It's my understanding that the `fd` and `eva_id` arguments to the driver functions are tightly coupled in meaning. For example, when you initialize with `hb_mc_init_device(fd,eva_id,fname,tile,ntiles)`,  is it not the case that the `eva_id` is tied to that `fd`? 

If my understanding is correct, right now different driver functions omit the `fd` argument if you don't need it. This exposes a little more to the users of this library than it should. What would be better is if there were a single type called `device_t` that is passed to all of these functions. Underneath the hood this could be a C struct that contains information relevant to memory allocation (like `eva_id`) and its low-level device descriptor `fd`.

**Comment by drichmond** [comment]
Fixed in spades in #213
