### ISSUE TITLE
Regression Tests for dev-cuda

### ISSUE THREAD

**Issue by ashwin-hari** [bespoke-silicon-group/bsg_f1#128]
The following functions/features were added in `dev-cuda` and should be unit tested.

Driver:

`hb_mc_eva_to_npa()`: The EVA may be a DRAM address or a Global Remote address that is in the host or in a tile. 

`hb_mc_npa_to_eva()`: The NPA may either be in DRAM, a tile, or the host.  

CUDA:

`hb_mc_device_memcpy()`: This function should be tested with DRAM and tile EVAs. It should also be tested with invalid device EVAs.

The API allows for a host program to launch different kernels with 8 or less arguments in succession on different tile groups.  A test that does this should be added.

**Comment by max-ruttenberg** [comment]
My understanding is that this being addressed in some branch off of `dev`?

**Comment by drichmond** [comment]
Yeah. When we merge in Borna's CUDA PR we'll close a lot of these issues.

**Comment by bornaehsani** [comment]
Addressed in PR #251 .
