### ISSUE TITLE
Convert tabs to spaces in all C/C++ code

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#141]
Not urgent, self explanatory

**Comment by bornaehsani** [comment]
This is to satisfy my curiosity, but why is this important?

**Comment by max-ruttenberg** [comment]
Why does the sun rise every day? There's an esoteric answer to this question: something about gravity and inertia. But it's easier to just accept that it does and move on with your life. I recommend adopting that philosophy here.

**Comment by max-ruttenberg** [comment]
In all seriousness though; I think it has to do with how editors render tabs. While spaces are more or less standard across editors, tabs are not. Which means that if your source file is indented with tabs it might not look the same to your collaborators as it does to you.

**Comment by bornaehsani** [comment]
Ha! Well that makes sense thanks for the philosophical and fun explanation :D but it'll take years to fix all files...

**Comment by max-ruttenberg** [comment]
> Ha! Well that makes sense thanks for the philosophical and fun explanation :D but it'll take years to fix all files...

* In the world? Sure. 
* In this repo? Nah -- it shouldn't be that bad. We have technology on our side.

A bigger problem is enforcement. Once we've addressed this issue how do we ensure that folks continue to use spaces instead of tabs? The internet has solutions...

**Comment by max-ruttenberg** [comment]
BTW: emacs has `M-x untabify` which will make short work of removing tabs in our current source files.

**Comment by sampsyo** [comment]
Or maybe something like this:

```
find . -name '*.c' -exec sed -i 's/\t/    /g' {} +
```

**Comment by max-ruttenberg** [comment]
dat's cool too... make's even faster work and doesn't require emacs.

**Comment by taylor-bsg** [comment]
We don't like tabs in bsg, but the challenge is to do this in a way that
does plays well with git history tracking and doesn't mess up github
gamification (i.e. taking credit for all of the lines of code). Generally I
would say that if you choose to detabify, do it on your code (for the
gamification aspect) or request that the author do it, and make the
detabification commit independent of a substantive code change (for history
tracking).

The other item is the trailing spaces, which emacs also can eliminate for
you with a single keypress. Here even more so than tabs, it is not worth
churning the code in the git repo history over this. If you are modifying
the line of code anyways, it is fine of course.

Not sure Adrian's command will play nicely with all of C (e.g., strings).

M
