### ISSUE TITLE
init-host should take a slot ID 

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#145]
https://github.com/bespoke-silicon-group/bsg_f1/blob/79151ff5580990f2cfff43f5c7bd790412bbf9f7/cl_manycore/libraries/bsg_manycore_driver.cpp#L145

Someday we may have multiple slots, in which case we need to initialize many slots.

**Comment by drichmond** [comment]
Fixed in #213, right @max-ruttenberg?

**Comment by max-ruttenberg** [comment]
[yep](https://github.com/bespoke-silicon-group/bsg_f1/blob/99d7e801bd67ee7f15c735fd7d85c450e271a810/cl_manycore/libraries/bsg_manycore.h#L54)

**Comment by drichmond** [comment]
Boom
