### ISSUE TITLE
Will the loader work if TEXT > 4kB

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#157]
https://github.com/bespoke-silicon-group/bsg_f1/blob/8d7948a04f2a20e07fedb87712a46407cfb6a9f3/cl_manycore/libraries/bsg_manycore_loader.cpp#L96

This for loop has the potential to write outside of the 4KB memory space. Or am I missing something?

**Comment by max-ruttenberg** [comment]
This discussion seems tightly coupled with #194

**Comment by drichmond** [comment]
Yep

I think anything related to the loader can be subsumed by #194

**Comment by drichmond** [comment]
Fixed in #213
