### ISSUE TITLE
[CUDA-Lite] Set X Y when kernel is loaded into tile group

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/bsg_f1#162]
https://github.com/bespoke-silicon-group/bsg_f1/blob/be0d7b91ebc6028e9e5ba0f7f8b653f4e9ab486d/cl_manycore/libraries/bsg_manycore_cuda.cpp#L290

This code should initialize the X and Y memory locations of the tile so we don't have to call bsg_set_x_y.

**Comment by bornaehsani** [comment]
Addressed in PR #251 .
