### ISSUE TITLE
Should cache properties be added to ROM?

### ISSUE THREAD

**Issue by save-buffer** [bespoke-silicon-group/bsg_f1#169]
In order to test writing to DRAM, we have to be able to flush the victim cache. There are two ways that I can think of: use an intrinsic (which doesn't exist), or write to a bunch of addresses that map to the same set, thereby flushing the cache line we want flushed. Tests interested in doing the latter option need to know the cache's properties. While we could just hard code them, I think it would be better to be able to read them from ROM.

**Comment by drichmond** [comment]
@save-buffer What if we passed the parameters as -D flags?

**Comment by save-buffer** [comment]
That works

**Comment by proftaylor** [comment]
Curious .. which cache properties and why?

M

**Comment by drichmond** [comment]
This is just for Regression Testing, so that our regression tests are fast in cosim. For example - we can cause a way to evict in WAYS+1 writes instead of WAYS*CACHE_LINES + 1 writes. 

I don't think they need to be defined in the ROM. The manycore cores shouldn't need them, right?

**Comment by proftaylor** [comment]
Not currently..

M
