### ISSUE TITLE
Refactor Program Loader

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#194]
The current program loader is monolithic, and unwieldy. It works - but it doesn't reuse other parts of the code that could be useful (memcpy), and could have bugs (writing past 1kW). 

Let's refactor it to handle EVA/EPA striping and modularize it without breaking the API.

**Comment by drichmond** [comment]
DMEM_BASE Should be dynamically determined too, if it can.

**Comment by max-ruttenberg** [comment]
Sure; let's refactor. I'm not crazy about the interface for device load. As @cylinbao has pointed out, the fact that it takes a file name argument instead of a data buffer requires us to open and read the file again at other points (see `symbol_to_eva` and `run_kernel`). 

I think the file name argument unnecessarily couples the act of loading data onto the manycore with where that data comes from. After all, maybe it's read out of a socket or something cool/insane like that.

**Comment by max-ruttenberg** [comment]
To avoid breaking people's code we could leave that function's interface as is but make another one called `load_program_data()` which takes a buffer argument. Then we can refactor the implementation of `load_binary()` to read the data from a file and call `load_program_data()`

**Comment by drichmond** [comment]
Was this fixed in the refactor? Should we determine the EVA for DMEM_BASE dynamically, or is it (relatively) static

**Comment by max-ruttenberg** [comment]
We determine the EVA from the ELF binary by using the program headers `p_vaddr` field. 

That means the loader punts the responsibility to the linker script + the `eva_map_t` type to tell it where things should go.

**Comment by drichmond** [comment]
But in EVA to NPA translation we use a macro for DMEM base. Should we?

**Comment by max-ruttenberg** [comment]
DMEM base is an EPA right? At the moment it's the only option we have I think. 
AFAIK there's no way to query the hardware where the EPA for the base of local memory is, so what else is there to do but have it as a constant?

**Comment by drichmond** [comment]
See: https://github.com/bespoke-silicon-group/bsg_f1/blob/99d7e801bd67ee7f15c735fd7d85c450e271a810/cl_manycore/libraries/bsg_manycore_eva.cpp#L60

and 
https://github.com/bespoke-silicon-group/bsg_f1/blob/99d7e801bd67ee7f15c735fd7d85c450e271a810/cl_manycore/libraries/bsg_manycore_tile.h#L27

**Comment by max-ruttenberg** [comment]
This is what we already do right? I guess what I'm saying is there's nothing else to do but what we do already without some help from hardware. 

It's not like the value of DMEM base is configurable or can be read from ROM.

**Comment by drichmond** [comment]
True. We don't necessarily have a program when doing EVA to NPA translation

We could read it from the ROM. That might be useful. Or it might be part of the EVA Map

**Comment by drichmond** [comment]
Regardless, i'll consider this issue closed and open a new one
