### ISSUE TITLE
Add axi interface wrapper for the bladerunner

### ISSUE THREAD

**Issue by leonardxiang** [bespoke-silicon-group/bsg_f1#196]
Now the bladerunner project has put separated modules at the toplevel, including concatenated intermediate AXI signals. It is confusing and hard to reuse the code.

I suggest to create a wrapper for the bladerunner, and expose only standard AXI interfaces to the outside word, i.e. the shell on F1 or the vcu128 PCIe interface.

**Comment by drichmond** [comment]
Closing, since this is old and not on our dev path at the moment
