### ISSUE TITLE
Expose port abstraction for manycore->host communication

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/bsg_f1#203]
Each address can be considered a port that can be used to demultiplex traffic that comes in over PCI-E. I believe we have about 64K addresses that we can use. Then a message dispatch loop can either call to a dispatch handler for a particular message, or place the message in a queue. This will allow us to process debug and other out-of-band messages while we are doing things like running the tilegroup scheduler.

Ports:

- ports for tile groups to communicate to the scheduler state changes
- ports for tiles in a tile group to write to using a putchar or integer print macros, for non-intrusive, 1-2 instruction printing capability. each tile in the tilegroup should get a unique ID so that we can demultiplex traffic between them.

- other ports for other classes of traffic we want to demultiplex (I/O? etc)

**Comment by drichmond** [comment]
Would you like a separate message demultiplexing thread on the host? Do you envision this happening as part of the CUDA API?

**Comment by taylor-bsg** [comment]
Currently I see it as being part of the host-side CUDA runtime.  In terms of separate threads, it is one conceivable architecture.  But I think we should start with the cooperatively threaded version, since synchronization is easier to do and easier to get right.

**Comment by max-ruttenberg** [comment]
Can we get a running list of these ports and their functions? I think that would be helpful for architecting a driver model.

**Comment by max-ruttenberg** [comment]
I think the place to start is, if we are just making this part of the **CUDA** runtime, having the call to `device_sync` spin on the FIFOs (which I'm pretty sure it already does) and field request packets other than just the one that means "I'm done". 

Right now it just drops those other packets.

For reference:
```c
void hb_mc_device_sync (uint8_t fd, hb_mc_request_packet_t *finish) {
	hb_mc_request_packet_t recv;
	/* wait for Manycore to send packet */
	while (1) {
		hb_mc_fifo_receive(fd, HB_MC_FIFO_RX_REQ, (hb_mc_packet_t *) &recv);
		
		if (hb_mc_request_packet_equals(&recv, finish) == HB_MC_SUCCESS) 
			break; /* finish packet received from Hammerblade Manycore */
	}	
}
```

**Comment by drichmond** [comment]
(For tracking purposes)

We would also like a port to send the current 64-bit counter to the host.
