### ISSUE TITLE
test_vcache_sequence: TMI

### ISSUE THREAD

**Issue by max-ruttenberg** [bespoke-silicon-group/bsg_f1#210]
`cl_manycore/regression/library/test_vcache_sequence.c`

This test takes a long time (esp. in COSIM) and prints out way too much.

Rather than printing out every single item in the vector with `Success` or `Failure`, it should just print out the indexes in which the host and device are not equal (so just failures).

**Comment by drichmond** [comment]
@bornaehsani Did you write this test?

**Comment by bornaehsani** [comment]
Yes I did, I will address Max's comment soon.

**Comment by bornaehsani** [comment]
Addressed in PR #266 .
