### ISSUE TITLE
regression logs; stderr please

### ISSUE THREAD

**Issue by max-ruttenberg** [bespoke-silicon-group/bsg_f1#223]
When I run `make regression` in `cl_manycore` and then look at the log files for each test, it seems that only the stdout output is captured. It would be really nice if those logs could also have stderr output too.

**Comment by drichmond** [comment]
Are you comfortable with reducing stderr to stdout if you want to capture stderr in the log?

**Comment by drichmond** [comment]
FIxed in #255
