### ISSUE TITLE
Location of DMEM Base

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#227]
Who determines the location of DMEM Base in the EVA Space? 

Will it ever change? 

We could read it from the ROM. That might be useful. Or it might be part of the EVA Map.

Right now it is statically defined as a macro in a header file. This is fine

**Comment by max-ruttenberg** [comment]
* Having it read from ROM seems harmless? I don't know what the overhead of that would be but I assume it would be very small. 
* Having it be configurable seems like a lot more work and extra logic for something that doesn't strike me as super valuable. But I'm open to be convinced.
