### ISSUE TITLE
Print a helpful message when there's an invalid configuration in ROM

### ISSUE THREAD

**Issue by max-ruttenberg** [bespoke-silicon-group/bsg_f1#229]
Right now on F1, this message appears when ROM info fails our internal sanity checks:
```
ERROR:   hb_mc_config_init: Invalid Device Dimension X -1
ERROR:   test_manycore_packets: hb_mc_manycore_init_config: Failed to initialize configuration fields of manycore struct
ERROR:   failed to initialize manycore: Failure
```

In practice this seems to happen when the user forgets to run `fpga-load-local-image` so maybe we should add an error message to above like:
`ERROR: Have you initialized your FPGA?`

**Comment by drichmond** [comment]
Fixed in #230
