### ISSUE TITLE
Add pause function to avoid infinite loop in cosim

### ISSUE THREAD

**Issue by leonardxiang** [bespoke-silicon-group/bsg_f1#233]
https://github.com/bespoke-silicon-group/bsg_f1/blob/c295db75fb4444fcd2ddb78ad68a25d5c85336d6/cl_manycore/libraries/bsg_manycore.cpp#L868-L876

**Comment by drichmond** [comment]
Does this solve the credit bug?

**Comment by leonardxiang** [comment]
In the credits fix PR #237, the test fails as expected, but the cosim can not terminate.
It turns out this is not the real reason for the simulation hang. I will make another one.
