### ISSUE TITLE
Port test_vcache_simplified, test_vcache_flush to new API

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#245]
I'd like to use these tests in the long run - they're much faster, and test the same behavior as vcache_sequence.

**Comment by drichmond** [comment]
Not urgent - when someone has 5-10 minutes

**Comment by bornaehsani** [comment]
I don't understand, they look like they are already ported

**Comment by drichmond** [comment]
Hmm. I guess the naming needs to match the new tests then.
