### ISSUE TITLE
Fix the number of stale packets based on the rx fifo occupancy 

### ISSUE THREAD

**Issue by leonardxiang** [bespoke-silicon-group/bsg_f1#246]
https://github.com/bespoke-silicon-group/bsg_f1/blob/ee84f764b48f5017d15589cdb5db1d45902cd394/cl_manycore/libraries/bsg_manycore.cpp#L161-L162

The rx fifo occupancy is in words, the number of stale manycore packets is occupancy/sizeof(packet)

**Comment by drichmond** [comment]
What makes you think the occupancy is in words? What is the width of the FIFO?

**Comment by leonardxiang** [comment]
The width of the FIFO is 32 bits, but the packet width is 128 bits. Am I right?

**Comment by drichmond** [comment]
The FIFO width is 32 bits?

**Comment by drichmond** [comment]
Okay, it's 32 bits. What's the issue?

**Comment by leonardxiang** [comment]
My understanding is that the **hb_mc_manycore_rx_fifo_drain()** function will check the occupancy (number of words left), and try to drain the rx fifo.
Since it calls the function **hb_mc_manycore_packet_rx()** which consumes 4 words per time. 
Then I think it should call the hb_mc_manycore_packet_rx occupancy/4 times, otherwise the program will hang.

**Comment by drichmond** [comment]
occupancy only returns the occupancy of the oldest packet received -- not all packets

**Comment by leonardxiang** [comment]
In the data sheet, it writes:
https://www.xilinx.com/support/documentation/ip_documentation/axi_fifo_mm_s/v4_1/pg080-axi-fifo-mm-s.pdf
**Receive Data FIFO Occupancy: This is the unsigned value reflecting a current snapshot of the number of locations in use for data storage in the receive Data FIFO memory core in the most recent transaction.**

But in the real experiment, the occupancy register will return the total number of locations in use of the rx fifo.

**Comment by drichmond** [comment]
Yes, but the end of that sentence also says: 

` If more than one packet is received,
a read to this register returns the number of
locations occupied by the latest received
packet.`

**Comment by leonardxiang** [comment]
Yes, I also noticed that. 
I recommend that you run the test_manycore_credits on the branch **credits_hangs** to checkout my observation.

**Comment by drichmond** [comment]
I think the drain method is correct, but hb_mc_manycore_rx_fifo_get_occupancy is wrong - it currently returns the word occupancy, not the packet occupancy. 

If the FIFO width were 128, this would be correct (though, always 1). However, it is not. 

The solution is to divide the occupancy by (FIFO_WIDTH/(sizeof(packet)*8)) inside of hb_mc_manycore_rx_fifo_get_occupancy

**Comment by drichmond** [comment]
Good find Leonard!

**Comment by leonardxiang** [comment]
> hb_mc_manycore_rx_fifo_get_occupancy

Thanks,

I but shouldn't we just use the original definition of the occupancy of the rx_fifo? 
Because the rx_fifo width is 32 bit anyway.

**Comment by drichmond** [comment]
Well, the current API says that hb_mc_manycore_rx_fifo_get_occupancy returns the number of unread packets in a FIFO, so I'm going to stick with that.

**Comment by leonardxiang** [comment]
I see.

**Comment by drichmond** [comment]
Addressed in #247
