### ISSUE TITLE
Outstanding Host Requests Capped at 32

### ISSUE THREAD

**Issue by mrutt92** [bespoke-silicon-group/bsg_f1#250]
https://github.com/bespoke-silicon-group/bsg_f1/blob/26d021ecd7d3d0d25718f63da14e9c528f236cf6/cl_manycore/libraries/bsg_manycore.cpp#L377

What's the correct way to know your FIFO depth? @leonardxiang can we add an AXI register?

**Comment by leonardxiang** [comment]
Hi, Max, the answer is always yes. We can add the fifo depth to the bladerunner ROM.

**Comment by drichmond** [comment]
We don't necessarily need to add it to the ROM. In the new BaseJump STL Host Interface it might make sense to provide a depth register that the host can read.
