### ISSUE TITLE
format_request_packet should check for invalid target

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#258]
https://github.com/bespoke-silicon-group/bsg_f1/blob/dbf65db99b9032df52baa7debe6cbd0b2d3c2d22/cl_manycore/libraries/bsg_manycore.cpp#L1111

And it should return HB_MC_INVALID if the destination is invalid.

**Comment by max-ruttenberg** [comment]
What's an invalid target? 
* I could check if the NPA maps to a valid EVA, but there are valid NPAs that don't have EVA mappings.
* I could hardcode checking of bits and coordinates here, but that seems like the wrong move engineering wise...

I think we'd talked offline about having a component mapper that maps NPAs to hardware components (e.g. DRAM, V-Core local memory, host, etc.). THAT sounds like just the tool for this job (if only it existed).

**Comment by drichmond** [comment]
I meant checking x/y destination. Where else would you put that if this is the wrong place?
