### ISSUE TITLE
update host api and interface for load_id_width_p=12

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/bsg_f1#259]

**Comment by drichmond** [comment]
Tommy, can you be more descriptive about what has changed, and how the host interface, and (maybe) software needs to adapt?

**Comment by tommydcjung** [comment]
I looked at current implementation, and I think it shouldn't affect the change in this parameter. One of the test looked as if it was hanging, because it was taking long time without printing anything.
