### ISSUE TITLE
use hb_mc_idx_t instead of uint8_t for tile coordinates

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#267]
https://github.com/bespoke-silicon-group/bsg_f1/blob/12617602a16b781418463f639d31abeb1adae9a0/cl_manycore/libraries/bsg_manycore_cuda.cpp#L40

(Unless these methods are deprecated)

**Comment by bornaehsani** [comment]
The method is deprecated, I forgot to add a tag to it. Thanks for pointing it out! I will remove the function in a separate PR that removes all deprecated functions.

**Comment by drichmond** [comment]
OK, is issue #267 still relevant then?

What about hb_mc_device_wait_for_tile_group_finish_any? It uses uint8_t's

**Comment by bornaehsani** [comment]
Addressed in PR #275 .
