### ISSUE TITLE
Create Freeze (and unfreeze?) Tile*s* Method

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#268]
https://github.com/bespoke-silicon-group/bsg_f1/blob/12617602a16b781418463f639d31abeb1adae9a0/cl_manycore/libraries/bsg_manycore_cuda.cpp#L745

This seems like a common function. If so, it should be factored out.

**Comment by bornaehsani** [comment]
Addressed in PR #275 .
