### ISSUE TITLE
Create tile_load method

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#270]
https://github.com/bespoke-silicon-group/bsg_f1/blob/12617602a16b781418463f639d31abeb1adae9a0/cl_manycore/libraries/bsg_manycore_cuda.cpp#L778

This method is very long, which makes it harder to maintain and understand. I think a simple fix would be to factor out the interior of the large while loop into a separate method that just loads a single tile

**Comment by bornaehsani** [comment]
Addressed in PR #275 .
