### ISSUE TITLE
Convert variables in hb_mc_memcpy_to_device to UPPER_CASE

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#271]
https://github.com/bespoke-silicon-group/bsg_f1/blob/12617602a16b781418463f639d31abeb1adae9a0/cl_manycore/libraries/bsg_manycore_cuda.h#L108

It seems that our implicit standard is to have all macros constants be UPPER CASE. I believe this is consistent with other coding styles.

**Comment by max-ruttenberg** [comment]
Yes, all constants (whether they are a macro, enum, or a const variable) should be upper case.

**Comment by bornaehsani** [comment]
Addressed in PR #275 .
