### ISSUE TITLE
Remove binary-specific functions from tile.h

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#272]
https://github.com/bespoke-silicon-group/bsg_f1/blob/45a6bc160f40c3f392d220f7be77c8bc8a0cd64f/cl_manycore/libraries/bsg_manycore_tile.h#L155

Since these are relevant to CUDA-Lite, I think they would be better to maintain in the cuda files.

tile.h just abstracts the configuration of a tile, and to me, it feels weird to have functions that require a CUDA binary.

@max-ruttenberg, Your thoughts?

**Comment by max-ruttenberg** [comment]
I don't know... `set_origin_registers` seems reasonable to have in it's current header. In general, I'm all for having a few small header files with descriptive names than one monolithic header. The functions for setting symbol values in the program seem pretty CUDA specific? @bornaehsani Do only CUDA programs have those symbols in the binary?

**Comment by drichmond** [comment]
Oops, I meant the functions like: 

https://github.com/bespoke-silicon-group/bsg_f1/blob/45a6bc160f40c3f392d220f7be77c8bc8a0cd64f/cl_manycore/libraries/bsg_manycore_tile.h#L174

(Which @max-ruttenberg correctly referenced)

**Comment by bornaehsani** [comment]
Addressed in PR #275 .
