### ISSUE TITLE
rom_data_lo used before declaration

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#276]
https://github.com/bespoke-silicon-group/bsg_f1/blob/92643b8c79e0cdab46b02f5415ac9191334efb81/hdl/bsg_bladerunner_rom.v#L110

**Comment by drichmond** [comment]
This causes a linting error

**Comment by leonardxiang** [comment]
Hi, Dustin, this module is not used after we move the manycore interface. ( But I fixed it anyway)
And it will be removed in PR #261.
