### ISSUE TITLE
Request for device init with 'all tiles' option

### ISSUE THREAD

**Issue by max-ruttenberg** [bespoke-silicon-group/bsg_f1#278]
Right now CUDA lite's `device_init` takes a coordinate argument. 
It would be nice if there were a way to just request that all available tiles be used.

**Comment by bornaehsani** [comment]
That's a good idea! I'll get it done!

**Comment by bornaehsani** [comment]
Changed hb_mc_device_init to no longer take in dimensions, and initialize device with maximum possible dimensions. 
Also added hb_mc_device_init_custom_dimensions to replace the old functions.
Addressed in PR #309.
