### ISSUE TITLE
device_init: make the char* const please

### ISSUE THREAD

**Issue by max-ruttenberg** [bespoke-silicon-group/bsg_f1#279]
The name parameter should be typed `const char *`.

https://github.com/bespoke-silicon-group/bsg_f1/blob/b5eaf17006ebef61e1bd7fda9154ac8aa951fdd2/cl_manycore/libraries/bsg_manycore_cuda.h#L123

**Comment by bornaehsani** [comment]
Addressed in PR #275 . Thanks!
