### ISSUE TITLE
Fix the host returning data to the manycore

### ISSUE THREAD

**Issue by leonardxiang** [bespoke-silicon-group/bsg_f1#299]
https://github.com/bespoke-silicon-group/bsg_f1/blob/fd9b3a4cb3b956d755d5433ab1ff193eb1efa050/hdl/axil_to_mcl.v#L426-L434

The host returning data format is wrong. 
Thanks for @tommydcjung to point this!

**Comment by drichmond** [comment]
Thanks Leonard!
