### ISSUE TITLE
Create new typedef hb_mc_handle_t to replace uint8_t "file descriptor"

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#3]
https://github.com/bespoke-silicon-group/bsg_f1/blob/7feb9a38b0248546ddc5560078afbd0d1cbe5274/cl_manycore/libraries/bsg_manycore_driver.c#L24

Please create a new typedef for `int` that replaces uint8_t. Use `int` so that we can return negative values in errors.

**Comment by max-ruttenberg** [comment]
This is still very much open right?

**Comment by drichmond** [comment]
Yes. I think this is becoming higher priority. 

Can you set up a meeting with @bornaehsani, @cylinbao, and myself to discuss the loader, device, and any other types we might need? 

Think of it as a manycore software planning meeting

**Comment by drichmond** [comment]
Fixed in #213
