### ISSUE TITLE
Request for bsg_print_int for the HOST/CUDA API

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_f1#310]
Requested by prof.mbt: 
- Similar to bsg_printf, but only send one word
- Print the coordinates of the tile calling bsg_print_int
- Print the word in {hex, decimal, floating point} format

**Comment by max-ruttenberg** [comment]
Cool beans.

**Comment by drichmond** [comment]
Addressed in #342
