### ISSUE TITLE
This is check is going to be too forgiving in no DRAM mode

### ISSUE THREAD

**Issue by max-ruttenberg** [bespoke-silicon-group/bsg_f1#315]
https://github.com/bespoke-silicon-group/bsg_f1/blob/726ede5ee3c1d85b7cf0dada676127777b0d1b3d/cl_manycore/libraries/bsg_manycore_eva.cpp#L319

**Comment by drichmond** [comment]
@max-ruttenberg  how so? Maybe related to #333?

**Comment by drichmond** [comment]
is this fixed?

**Comment by max-ruttenberg** [comment]
I honestly don't know. I was way too vague when I posted this issue. Let's close it.
