### ISSUE TITLE
Rewrite configuration init to handle no-dram mode

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#324]

**Comment by bornaehsani** [comment]
We also need to set the correct dram size in both dram/no-dram modes, when the manycore hb_mc_config_t struct is initialized. The cuda memory allocator should throw an error if it runs out of space (which it doesn't right now, causing memory locations to get overwritten and tiles to run with wrong symbol values  and spin out of control with invalid EVA accesses)

https://github.com/bespoke-silicon-group/bsg_f1/blob/master/cl_manycore/libraries/bsg_manycore_cuda.cpp#L1295

**Comment by drichmond** [comment]
Related to #333

**Comment by drichmond** [comment]
@bornaehsani I think this is related to our discussion yesterday. Yes?

**Comment by bornaehsani** [comment]
Very much yes, if we include a parameter dram/no-dram inside ROM, the CUDA API can call hb_mc_disable_dram inside device_init, which means we will not need two versions of each regression tests.

**Comment by max-ruttenberg** [comment]
We were discussing this earlier. What was the conclusion?

**Comment by drichmond** [comment]
@bornaehsani @mrutt92 I think this is solved, right?
