### ISSUE TITLE
Obsolete Option in Makefile.vcs

### ISSUE THREAD

**Issue by xy97cornell** [bespoke-silicon-group/bsg_f1#334]
Running `make cosim` in `/cl_manycore/testbenches` led to this problem: 
`-M -I +lint=TFIPC-L -ntb_opts tb_timescale=1ps/1ps -timescale=1ps/1ps -sverilog -full64 +memcbk -licqueue -lca -v2005  -debug_pp -o /work/bsg_bladerunnerv3.0.6/bsg_bladerunner/bsg_f1_5160ca3/cl_manycore//testbenches//library//test_unified_main -l compile.vcs.log
Error-[OBSOLETE_OPTION]`` Obsolete option used
  The specified option '-I' is no longer supported.
  Please use '-debug_access+nomemcbk+dmptf -debug_region+cell' instead.`
This option is in Makefile.vcs in `/cl_manycore/testbenches` directory around line 52. 

My compiler version is: `VCS-MX O-2018.09-SP2`

**Comment by drichmond** [comment]
Thanks!
