### ISSUE TITLE
Add support for striping in EVA Translation API

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#335]
Description provided by MBT: 

For X-is-a-power -of-two arrays, cache line blocks are low order striped across the victim caches, ie cache line block 0 goes to victim cache 0, 1 to 1, cache block 8 goes to victim cache 0, etc. For X=9, the function is a little more complicated, with VC 8 subbing in for the others on a rotating basis. Tommy can point you guys at his loader code that does EVA to NPA translation.
And answer any questions

**Comment by bornaehsani** [comment]
Addressed in PR #344 .
