### ISSUE TITLE
Print cycles/second when cosimulation terminates

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#339]

**Comment by taylor-bsg** [comment]
Cycles per wall clock second? Or..?

**Comment by drichmond** [comment]
My intent was cycles per wall clock second. But, I'm open to other suggestions. We could also print it out at an arbitrary interval so that we get a trace of when cosimulation speeds up and slows down.

**Comment by taylor-bsg** [comment]
Maybe just wall clock time? I don’t know how cycles per wall second would
be useful?

**Comment by drichmond** [comment]
I thought you asked for this in the past. At the very least, this was requested in the meeting yesterday.
