### ISSUE TITLE
Non-C++ friendly header for regression tests

### ISSUE THREAD

**Issue by max-ruttenberg** [bespoke-silicon-group/bsg_f1#359]
https://github.com/bespoke-silicon-group/bsg_f1/blob/67d4e3f1b5e0bda64ad2522fcfdb131e7c4729a9/cl_manycore/regression/cl_manycore_regression.h#L151

Now that C++ regression tests are supported, C++-illegal lines of code such as above should be removed from headers in regression tests. Additionally an `extern "C"` guard should be added.

**Comment by max-ruttenberg** [comment]
To be clear, the posted line of code is illegal because C++ does not allow implicit pointer casting. In the above code `state->input` is a `void *`.

**Comment by drichmond** [comment]
Is this a simple fix? Can you make a PR, if so?

**Comment by drichmond** [comment]
Addressed in #360
