### ISSUE TITLE
Implement `hb_mc_device_init`

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#39]
The `hb_mc_device_init` function will: 
 - Take an eva_id and .elf file as a parameter
 - Load the binary
 - Initialize a malloc manager object
 - Unfreeze the tiles in a tile group. 
 - Initialize the tiles in a tile group with the specified EVA (future feature)

**Comment by bornaehsani** [comment]
Addressed in PR #251 .
