### ISSUE TITLE
RAND_MAX undeclared error in COSIM

### ISSUE THREAD

**Issue by leonardxiang** [bespoke-silicon-group/bsg_f1#423]
F1 cosim failed due to the undeclared macro. Below is the error message:

/home/xlelephant/git_repos/bsg_bladerunner/bsg_f1/regression/library//../cl_manycore_regression.h: In function 'hb_mc_generate_float_rand':
/home/xlelephant/git_repos/bsg_bladerunner/bsg_f1/regression/library//../cl_manycore_regression.h:144:46: error: 'RAND_MAX' undeclared (first use in this function)
  data.hb_mc_int = rand() * (((float)rand() / RAND_MAX) > 0.5 ? 1 : -1) ;
                                              ^
/home/xlelephant/git_repos/bsg_bladerunner/bsg_f1/regression/library//../cl_manycore_regression.h:144:46: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [test_rom.o] Error 1
make[1]: *** [product_clean_order] Error 2
make[1]: Leaving directory `/home/xlelephant/git_repos/bsg_bladerunner/bsg_f1/testbenches/library/test_rom.tmp'
Make exited with status 2
CPU time: 5.744 seconds to compile + .665 seconds to elab + .105 seconds to link

 common elaboration failed
make: *** [/home/xlelephant/git_repos/bsg_bladerunner/bsg_f1/testbenches/library/test_rom] Error 255

**Comment by bornaehsani** [comment]
My bad Leonard, thanks for pointing it out! Addressed in PR #424.
