### ISSUE TITLE
Bsg_f1 is out of sync with bsg_manycore

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_f1#444]
With PR # 190 (bsg manycore mem cfg) merged in bsg_manycore, the filelist and hardware in bsg_f1 is out of sync. Could you guys please take a look this? Thanks!

**Comment by drichmond** [comment]
We’ve never promised that bsg manycore and F1 master are in sync. That’s the point of bladerunner 

But we know of the issue and we’re working to fix it

**Comment by bornaehsani** [comment]
Cool, thanks!

**Comment by drichmond** [comment]
Addressed in #445
