### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#448]
As discussed on Monday, we're considering renaming this repository. Originally bsg_f1 had all of our F1 infrastructure in it, but that has changed in the last couple months as I have cleaned and focused the repository. 

hb_emulator
hb_fpga (I think all of our FPGA code will be in this repository)
hb_runner (Manycore is the Blade, this is the Runner)
hb_ostrich (Because Emu is off limits)

Thoughts? Suggestions? Ideas?

**Comment by drichmond** [comment]
I haven't put thought into it yet.

**Comment by dpetrisko** [comment]
Not to derail the renaming conversation, I'm just wondering if it makes sense to
1) Have two (three?) repos bp_f1, hb_f1, (bsg_f1?)
2) Have one repo bsg_f1 which has subdirectories for bp_f1 and hb_f1

**Comment by taylor-bsg** [comment]
What is in the bsg_f1 repository right now? It has the CuDA lite runtime
and f1 and cosimulation support, is that right?


M

**Comment by drichmond** [comment]
And the hardware for connecting manycore to F1

**Comment by taylor-bsg** [comment]
Revised:

A. {firmware+driver} X platforms { f1, asic cloud, HBM board, HB board }

B. CuDA lite runtime (could run on BP or Xeon)

C. host interface software (Xeon+PCiE, cosim, minimal)

Is this missing anything?

**Comment by drichmond** [comment]
How about hb_replicant?

**Comment by tommydcjung** [comment]
my vote goes to hb_wiley_e_coyote_roadrunner.

**Comment by drichmond** [comment]
Is that an enum?

(Bad joke, I've been reading the BSG Style guide recently)

**Comment by save-buffer** [comment]
I propose we move to a power ranger theme:
```
bsg_f1 -> bsg_command_center
bsg_manycore -> bsg_megazord
bsg_cadenv -> bsg_bcu (Katie's idea, bcu = bsg cinematic universe)
```

**Comment by drichmond** [comment]
Renaming to bsg_replicant with v3.6.0
