### ISSUE TITLE
Rename application_init to tile_group_enqueue

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#456]
To me, application init suggests initialization- parsing, loading, setup. However, it looks like application init actually enqueues tilegroups onto a host queue. 

I like to suggest renaming it for clarity, since it really confused me when I tried to execute a tile group repeatedly.

**Comment by taylor-bsg** [comment]
agree

**Comment by bornaehsani** [comment]
A very good point, addressed in PR #461 . Thanks!
