### ISSUE TITLE
byte/half/word memory access regression test from vcache and tile DMEM

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/bsg_f1#470]
would be really nice.

**Comment by mrutt92** [comment]
I'm not sure we ever got this feature working from the host?

**Comment by save-buffer** [comment]
I thought that addresses were always word-level, no? Page 7 of the Hammerblade Manycore Technical Reference Manual says:
> These word-level accesses go out onto the 2-D mesh network to the remote tile, cache or dram that owns the address in question.

**Comment by mrutt92** [comment]
Request packets have a mask field to select which bytes you actually want to read/write.

**Comment by mrutt92** [comment]
But yes, the network is word addressable.

**Comment by save-buffer** [comment]
Ok so we just want to test the mask handling?

**Comment by tommydcjung** [comment]
for store it would use mask field, but for load, load_info in payload has fields to include low 2-bits of address, byte_op, half_op.

**Comment by drichmond** [comment]
Half addressed by #468. DMEM to-be-addressed. Superseded by #476
