### ISSUE TITLE
test_manycore_vcache_sequence fails, throws assert 

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#477]
`bsg_manycore.cpp:1382: int hb_mc_manycore_write(hb_mc_manycore_t*, const hb_mc_npa_t*, const void*, size_t): Assertion 'shift == 0' failed.`

This is because it is trying to write an unaligned 4-byte word. @save-buffer, @bornaehsani and I are discussing solutions.

Filing for tracking purposes

**Comment by bornaehsani** [comment]
Addressed in PR #478 .
