### ISSUE TITLE
Python API that Mimics C/C++ API (for TVM)

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#49]
Open for discussion. This was discussed previously and should be simple with a well-engineered C API (like the one @ashwin-hari  is writing 👍 )

Please mark as `Nope` if the conclusion is that we should not support this.

**Comment by bornaehsani** [comment]
Is this issue stale?

**Comment by drichmond** [comment]
Probably? I think it'd be useful to have a python interface (for TVM or not), but I don't think any of us have the time to create one

**Comment by drichmond** [comment]
Perhaps this is useful for Cornell. @xy97cornell?
