### ISSUE TITLE
One memory manager per PCIe slot

### ISSUE THREAD

**Issue by ashwin-hari** [bespoke-silicon-group/bsg_f1#90]
https://github.com/bespoke-silicon-group/bsg_f1/blob/b15423845a81f05858d7e4061d47b4707237ff33/cl_manycore/libraries/bsg_manycore_driver.cpp#L44

The mapping should from `fd` to Memory Manager and not from `eva id`.

**Comment by bornaehsani** [comment]
Out of date, addressed in PR #251 .
