### ISSUE TITLE
Should not pass in binary in launch function

### ISSUE THREAD

**Issue by ashwin-hari** [bespoke-silicon-group/bsg_f1#91]
https://github.com/bespoke-silicon-group/bsg_f1/blob/b15423845a81f05858d7e4061d47b4707237ff33/cl_manycore/libraries/bsg_manycore_driver.h#L64

The API should keep a mapping from `fd` to binary so that the binary does not have to be passed in.

**Comment by drichmond** [comment]
Fixed in #213
