### ISSUE TITLE
Should hb_mc_device_malloc() return pointer rather than eva_t (uint32_t)?

### ISSUE THREAD

**Issue by cylinbao** [bespoke-silicon-group/bsg_f1#97]
https://github.com/bespoke-silicon-group/bsg_f1/blob/b15423845a81f05858d7e4061d47b4707237ff33/cl_manycore/libraries/bsg_manycore_driver.h#L59
https://github.com/bespoke-silicon-group/bsg_f1/blob/b15423845a81f05858d7e4061d47b4707237ff33/cl_manycore/libraries/bsg_manycore_driver.h#L60
Should these two functions use the void* to return or pass the memory address rather than using eva_t?

https://github.com/bespoke-silicon-group/bsg_f1/blob/b15423845a81f05858d7e4061d47b4707237ff33/cl_manycore/libraries/bsg_manycore_driver.h#L109
Since the hb_mc_device_memcpy() uses the void* to pass dst and src.
Also, by using void*, it will be easier to communicate with the host program where is usually 64-bit machine.

**Comment by drichmond** [comment]
Since nobody has responded in a month, I'm considering this stale and closing it.
